<button onclick="topFunction()" id="topbtn" title="Go to top"><i class="fa-solid fa-arrow-up"></i></button>
<header style="position: sticky; top: 0;">
	<div id="navbar"><div style="max-width: 1000px; margin: auto;">
		<img id="logo" onclick="location.href='index.php';" src="styles/images/logo.svg">
		<a id="menulink" href="index.php" class="active">Головна</a>
		<a id="text-login" class="lnk" href="login.php">Увійти</a>
		<a id="icon-login" class="lnk" href="login.php" style="width: 24px; text-align: center;"><i class="fa-solid fa-user"></i></a>
	</div></div>
<div class="progress-container">
	<div class="progress-bar" id="myBar"></div>
</div>
</header>

<div class="textbox">
<a href="videos/player">player</a>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eleifend posuere ipsum sit amet egestas. Sed nisl neque, blandit et enim sollicitudin, ullamcorper faucibus ante. Nullam hendrerit ex eu tincidunt suscipit. Etiam aliquet eros mi, at posuere velit sagittis at. Cras vel dui enim. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras vel nisl eget est cursus iaculis non at nulla. Etiam non mauris ac enim tristique porttitor. Cras rhoncus nulla nunc, ut fermentum odio placerat ut. Donec auctor volutpat dolor, eu consectetur augue imperdiet eget. Aliquam ac velit purus. Praesent est est, lacinia vel maximus et, lacinia vel odio. Sed ipsum neque, fringilla at auctor id, ullamcorper vitae leo. Sed accumsan ultrices tortor ut luctus.</p>
<p>Aenean ut enim mauris. Cras convallis faucibus purus at sagittis. Morbi nulla risus, ullamcorper id ligula at, gravida facilisis sem. Phasellus viverra ornare vulputate. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse malesuada elit sit amet lorem blandit, et ornare odio gravida. Etiam nisi risus, scelerisque et sapien ac, ultricies mollis tellus. Aliquam neque mauris, iaculis ac pretium non, sodales non augue. Vivamus eleifend eros velit, non faucibus ipsum malesuada quis.</p>
<p>Praesent id erat risus. Vestibulum vitae elit vehicula neque pulvinar sodales vehicula non nunc. Phasellus placerat, lorem vitae consequat tempus, nisi quam sagittis nibh, ut commodo lorem orci a tellus. Etiam magna dui, blandit vitae ipsum quis, sollicitudin pretium enim. Curabitur nec sollicitudin eros. Nunc vel facilisis nulla. Duis vestibulum ligula in lacus molestie, ut consequat mauris varius. Suspendisse sit amet ligula maximus nibh egestas bibendum luctus et mauris. In commodo leo cursus turpis semper, id consectetur nisl aliquam. Vestibulum vitae mi magna. Pellentesque blandit lectus augue, quis vestibulum lectus consequat eu. Morbi facilisis felis ac tincidunt mollis. Fusce fringilla nibh eget nisi porta imperdiet. Fusce ultricies, sem a faucibus porttitor, lectus massa euismod magna, eget vestibulum augue dolor in lectus.</p>
<p>Praesent feugiat eros scelerisque mi dignissim, non porta lorem volutpat. Quisque maximus erat pellentesque orci venenatis, sit amet volutpat purus scelerisque. Vestibulum ut malesuada est. In hac habitasse platea dictumst. Aliquam nec metus nec tortor aliquet fringilla. Aenean lacinia tempus nisl ut lobortis. Sed at lorem efficitur nulla dictum hendrerit eget dapibus justo. Etiam non ante vel turpis dignissim euismod a nec nisi. Sed id urna sollicitudin, facilisis arcu et, auctor nisl. Duis vel magna enim. Pellentesque ullamcorper aliquet sollicitudin. Quisque in viverra leo. In eu gravida sapien, efficitur mattis lorem. Vestibulum lorem est, rhoncus eu faucibus ut, faucibus ut arcu.</p>
<p>Donec a dolor at quam pulvinar egestas eget sed arcu. Aenean sollicitudin ipsum tellus, at scelerisque elit porttitor in. Suspendisse mattis malesuada mi vitae vulputate. Aliquam urna tortor, finibus nec orci vitae, laoreet bibendum diam. Quisque elementum dolor vitae orci ultrices, quis aliquam eros pulvinar. Mauris venenatis quam erat, id efficitur quam bibendum at. Aenean dictum tortor mauris, eget accumsan enim pharetra a. Aliquam erat volutpat.</p>
<p>Quisque volutpat, erat ultrices feugiat mattis, odio massa pharetra odio, ut iaculis libero ante vehicula orci. Morbi sit amet tristique sem. In sit amet venenatis purus, quis aliquam nibh. Aliquam nunc sapien, rhoncus eu erat non, semper fermentum lectus. Vivamus nibh erat, scelerisque vel quam at, rutrum dignissim turpis. In ultrices malesuada nisi, ut sollicitudin dolor. Donec tincidunt tortor ac ex mollis mollis. In lectus odio, eleifend at ipsum in, pretium congue ligula. Vivamus quis neque hendrerit, blandit tortor ut, ornare odio. Quisque sed euismod ipsum. Duis erat dui, blandit vitae massa a, dapibus venenatis quam. Aliquam erat volutpat. Curabitur quis libero tortor. Suspendisse in feugiat odio, vitae porttitor arcu.</p>
<p>Nullam suscipit cursus quam id tempus. Nunc viverra sapien ac maximus fringilla. Mauris sit amet feugiat felis. Suspendisse odio quam, condimentum sit amet neque in, hendrerit mollis sem. Sed semper lacinia purus porta molestie. Ut aliquam lobortis lectus, id volutpat arcu blandit in. Nulla nec erat sapien. Ut tristique lacus nunc, ac consequat justo auctor eget. Nam eget laoreet sapien. Sed tellus magna, posuere eget luctus nec, interdum at arcu. Ut sit amet laoreet odio. Nullam molestie velit ligula, id imperdiet nulla dapibus eget.</p>
<p>Phasellus iaculis magna ut vulputate porta. Nam ullamcorper, risus at porttitor suscipit, tortor tortor sollicitudin odio, et luctus lectus augue sed orci. Praesent quis tellus finibus ipsum iaculis bibendum at non sem. Sed ac purus ipsum. Suspendisse egestas lorem tempus commodo rhoncus. Pellentesque vitae turpis luctus, elementum urna sit amet, ornare nisi. Nulla sodales enim non auctor iaculis. Aliquam ac magna vel augue semper euismod. Nam nisi quam, congue luctus interdum sagittis, sollicitudin nec tortor. Vivamus elementum gravida eros, non porta tellus placerat quis. Pellentesque eu urna neque. Donec id lorem accumsan, finibus elit nec, interdum odio. Aliquam erat volutpat. In hac habitasse platea dictumst. Proin dictum molestie diam sed condimentum. In ultrices lacinia quam, eget malesuada libero imperdiet vel.</p>
<p>Aliquam tincidunt justo et lorem malesuada mattis. Phasellus quis hendrerit turpis, vel aliquam nibh. Fusce in metus et lorem mattis varius. Quisque interdum at quam eu placerat. Nam eget nisi sed odio sodales dapibus sed sit amet velit. Praesent quis imperdiet nisi, in porta ex. Mauris ac dolor commodo, ornare lacus id, tincidunt est. Curabitur hendrerit vulputate mauris eu ullamcorper. Nullam lacus magna, tempus non augue ac, dignissim ultrices tellus. Etiam et tristique tellus. Ut luctus sodales ipsum. Duis ante mi, tempus quis lorem nec, volutpat malesuada eros. Donec sed pellentesque massa. Duis elit nisi, convallis vitae mauris ac, rutrum luctus felis. Vestibulum et ipsum in ipsum scelerisque lacinia.</p>
<p>Nullam lorem libero, commodo vitae neque sed, varius malesuada urna. Curabitur posuere tortor risus, vel facilisis orci dapibus vitae. Vivamus ornare non neque lacinia viverra. Sed tristique lorem nisi, vel lobortis urna semper eget. Integer id mauris nibh. Morbi volutpat gravida est, eget convallis nunc sollicitudin non. Sed luctus ut enim in fringilla. Sed id varius nisi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam sit amet orci sit amet magna lobortis dapibus quis sed dolor.</p>
</div>
<?php ?>
